name: Tests
on: ["push", "pull_request"]
jobs:
  build:
    strategy:
      matrix:
        java: ['11', '17', '21']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run tests
        run: ./gradlew check