name: Tests
on:
  push:
    branches:
    - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: 'JDK ${{ matrix.java }} on ${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        java: ['11', '17', '21', '24']
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: |
            ${{ matrix.java }}
            21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run tests
        run: ./gradlew check
        env:
          TESTING_AGAINST_JDK: ${{ matrix.java }}

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          annotate_only: true
          detailed_summary: true
          include_passed: true
          report_paths: '**/build/test-results/test/TEST-*.xml'