name: Tests
on: ["push", "pull_request"]
jobs:
  test:
    name: 'JDK ${{ matrix.java }} on ${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        java: ['11', '17', '21']
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: |
            ${{ matrix.java }}
            21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run tests
        run: ./gradlew check
        env:
          JAVA_HOME_OVERRIDE_VAR: JAVA_HOME_${{ matrix.java }}_X64

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          annotate_only: true
          detailed_summary: true
          include_passed: true
          report_paths: '**/build/test-results/test/TEST-*.xml'