name: Tests
on: ["push", "pull_request"]
jobs:
  test:
    name: Test with JDK ${{ matrix.java }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: ['17', '21']
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: |
            ${{ matrix.java }}
            21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run tests
        run: ./gradlew check
        env:
          JAVA_HOME_OVERRIDE_VAR: JAVA_HOME_${{ matrix.java }}_X64